Repository dylandoamaral/zio-selenium, pull requests merged in 2020-11, with the labels that each got.

#36 Improve webdriver creation
  README.md
  src/main/scala/zinteract/examples/FindElement.scala
  src/main/scala/zinteract/examples/InteractElement.scala
  src/main/scala/zinteract/examples/Link.scala
  src/main/scala/zinteract/webdriver/Blueprint.scala
  src/main/scala/zinteract/webdriver/Builder.scala
  src/main/scala/zinteract/webdriver/package.scala
  src/test/resources/BuilderSpec.html
  src/test/scala/zinteract/webdriver/ChromeBlueprintSpec.scala
  src/test/scala/zinteract/webdriver/TestDriver.scala
Labels: enhancement, refactor

#38 Add codecov configuration
  .codecov.yml
Labels: enhancement

#41 Add caching for sbt and coursier
  .github/workflows/scala.yml
Labels: refactor

#42 Add scaladoc
  src/main/scala/zinteract/alert/package.scala
  src/main/scala/zinteract/context/Wait.scala
  src/main/scala/zinteract/context/package.scala
  src/main/scala/zinteract/element/package.scala
  src/main/scala/zinteract/session/package.scala
  src/main/scala/zinteract/webdriver/Blueprint.scala
  src/main/scala/zinteract/webdriver/Builder.scala
  src/main/scala/zinteract/webdriver/package.scala
Labels: enhancement

#44 Upgrade packages
  build.sbt
  src/main/scala/zinteract/session/package.scala
Labels: refactor

#45 Add session layer to builder buildLayer
  README.md
  src/main/scala/zinteract/examples/FindElement.scala
  src/main/scala/zinteract/examples/InteractElement.scala
  src/main/scala/zinteract/examples/Link.scala
  src/main/scala/zinteract/webdriver/Builder.scala
Labels: refactor

#46 Add builder syntax and rename and alias for blueprints
  README.md
  src/main/scala/zinteract/examples/FindElement.scala
  src/main/scala/zinteract/examples/InteractElement.scala
  src/main/scala/zinteract/examples/Link.scala
  src/main/scala/zinteract/webdriver/Blueprint.scala
  src/main/scala/zinteract/webdriver/Builder.scala
  src/test/scala/zinteract/webdriver/ChromeBuilderSpec.scala
Labels: refactor

#47 Add chromedriver test
  .github/workflows/ci.yml
  .github/workflows/scala.yml
  build.sbt
  src/test/scala/zinteract/webdriver/WebdriverSpec.scala
Labels: test

#48 Merge both CI actions
  .github/workflows/ci.yml
  .github/workflows/scala.yml
  README.md
  build.sbt
Labels: refactor

#49 Add more tests
  src/main/scala/zinteract/context/package.scala
  src/main/scala/zinteract/element/package.scala
  src/main/scala/zinteract/session/package.scala
  src/test/resources/ElementSpec.html
  src/test/scala/zinteract/context/WaitSpec.scala
  src/test/scala/zinteract/element/ElementSpec.scala
  src/test/scala/zinteract/webdriver/ChromeBuilderSpec.scala
Labels: test

#51 Add firefox driver
  .codecov.yml
  .github/workflows/ci.yml
  build.sbt
  src/main/scala/zinteract/webdriver/Blueprint.scala
  src/main/scala/zinteract/webdriver/Builder.scala
  src/test/scala/zinteract/webdriver/BuilderUtils.scala
  src/test/scala/zinteract/webdriver/ChromeBuilderSpec.scala
  src/test/scala/zinteract/webdriver/FirefoxBuilderSpec.scala
  src/test/scala/zinteract/webdriver/WebdriverSpec.scala
Labels: enhancement

#52 Release v0.1.1
  CHANGELOG.md
  README.md
  src/main/scala/zinteract/examples/FindElement.scala
  src/main/scala/zinteract/examples/InteractElement.scala
  src/main/scala/zinteract/examples/Link.scala
Labels: release

#56 Remove session to webdriver accessor methods
  README.md
  src/main/scala/zinteract/examples/FindElement.scala
  src/main/scala/zinteract/examples/InteractElement.scala
  src/main/scala/zinteract/examples/Link.scala
  src/main/scala/zinteract/session/package.scala
  src/main/scala/zinteract/webdriver/Builder.scala
  src/main/scala/zinteract/webdriver/package.scala
  src/test/resources/WebDriverSpec.html
  src/test/scala/zinteract/alert/AlertSpec.scala
  src/test/scala/zinteract/context/WaitSpec.scala
  src/test/scala/zinteract/element/ElementSpec.scala
  src/test/scala/zinteract/session/SessionSpec.scala
  src/test/scala/zinteract/webdriver/TestDriver.scala
  src/test/scala/zinteract/webdriver/WebDriverLayerSpec.scala
  src/test/scala/zinteract/webdriver/WebDriverSpec.scala
Labels: refactor

#57 Move builder and blueprint to builder package
  README.md
  src/main/scala/zinteract/builder/Blueprint.scala
  src/main/scala/zinteract/builder/package.scala
  src/main/scala/zinteract/examples/FindElement.scala
  src/main/scala/zinteract/examples/InteractElement.scala
  src/main/scala/zinteract/examples/Link.scala
  src/main/scala/zinteract/webdriver/Builder.scala
  src/test/scala/zinteract/builder/BuilderSpec.scala
  src/test/scala/zinteract/builder/BuilderUtils.scala
  src/test/scala/zinteract/builder/ChromeBuilderSpec.scala
  src/test/scala/zinteract/builder/FirefoxBuilderSpec.scala
Labels: refactor

#66 Add mergify
  .mergify.yml
Labels: enhancement

#67 Add Scala Steward
  README.md
Labels: enhancement

#68 Add label to Scala Steward's PR
  .mergify.yml
Labels: refactor

#69 Fix add-path by upgrading setup-gpg actions
  .github/workflows/ci.yml
  build.sbt
Labels: bug, dependency upgrade

#70 Update sbt-github-actions to 0.9.5
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependency upgrade

#71 Add a DSL for a new By selector
  src/main/scala/zinteract/context/Selector.scala
  src/main/scala/zinteract/examples/Selector.scala
  src/test/resources/AttributeSelectorSpec.html
  src/test/resources/FlagSelectorSpec.html
  src/test/resources/LogicSelectorSpec.html
  src/test/resources/TagSelectorSpec.html
  src/test/scala/zinteract/context/SelectorSpec.scala
Labels: enhancement

#72 Release v0.2.0
  CHANGELOG.md
  README.md
Labels: release

#73 Add organize imports
  .scalafix.conf
  .scalafmt.conf
  build.sbt
  src/main/scala/zinteract/alert/package.scala
  src/main/scala/zinteract/builder/Blueprint.scala
  src/main/scala/zinteract/builder/package.scala
  src/main/scala/zinteract/context/package.scala
  src/main/scala/zinteract/element/package.scala
  src/main/scala/zinteract/examples/FindElement.scala
  src/main/scala/zinteract/examples/InteractElement.scala
  src/main/scala/zinteract/examples/Link.scala
  src/main/scala/zinteract/examples/Selector.scala
  src/main/scala/zinteract/webdriver/package.scala
  src/test/scala/zinteract/alert/AlertSpec.scala
  src/test/scala/zinteract/builder/BuilderSpec.scala
  src/test/scala/zinteract/builder/BuilderUtils.scala
  src/test/scala/zinteract/builder/ChromeBuilderSpec.scala
  src/test/scala/zinteract/builder/FirefoxBuilderSpec.scala
  src/test/scala/zinteract/context/SelectorSpec.scala
  src/test/scala/zinteract/context/WaitSpec.scala
  src/test/scala/zinteract/element/ElementSpec.scala
  src/test/scala/zinteract/webdriver/TestDriver.scala
  src/test/scala/zinteract/webdriver/WebDriverSpec.scala
Labels: enhancement
